config_files.settings:
  path: '/admin/config/development/configuration/tools'
  defaults:
    _form: '\Drupal\config_files\ConfigFilesSettingsForm'
    _title: 'Files Configuration'
  requirements:
    _permission: 'administer config_files'