name: Git Configuration
type: module
description: 'Stores configuration in a git repository.'
package: Configuration
# version: VERSION
# core: 8.x
configure: git_config.settings
dependencies:
  - config_files


# Information added by Drupal.org packaging script on 2014-10-27
version: '8.x-1.0-alpha3'
core: '8.x'
project: 'config_tools'
datestamp: 1414433031
