git_config.settings:
  path: '/admin/config/development/configuration/tools/git_configuration'
  defaults:
    _form: '\Drupal\git_config\GitConfigSettingsForm'
    _title: 'Git Configuration'
  requirements:
    _permission: 'administer git_config'