name: Configuration Synchronizer
type: module
description: 'Synchronize your site with updated configuration provided by modules and themes.'
# core: 8.x
dependencies:
 - config_update
 
# Information added by Drupal.org packaging script on 2015-11-29
version: '8.x-1.x-dev'
core: '8.x'
project: 'config_sync'
datestamp: 1448774640
