name: Menu link config
type: module
description: 'Allows to create menu links as config'
package: Menu
# version: VERSION
# core: 8.x

# Information added by Drupal.org packaging script on 2015-12-20
version: '8.x-1.x-dev'
core: '8.x'
project: 'menu_link_config'
datestamp: 1450632843
