menu_link_config.link_add:
  path: '/admin/structure/menu/manage/{menu}/add_config_link'
  defaults:
    _controller: '\Drupal\menu_link_config\Controller\MenuController::addLink'
    _title: 'Add menu link config'
  requirements:
    _entity_create_access: 'menu_link_config'

entity.menu_link_config.edit_form:
  path: '/admin/structure/menu/link/{menu_link_plugin}/edit'
  defaults:
    _form: 'Drupal\menu_ui\Form\MenuLinkEditForm'
    _title: 'Edit menu link'
  options:
    parameters:
      menu_link_plugin:
        type: menu_link_plugin
  requirements:
    _permission: 'administer menu'
