name: 'Configuration Inspector'
type: module
description: 'Provides a configuration data and structure inspector tool.'
package: Development
configure: config_inspector.overview
# core: 8.x
dependencies:
  - config

# Information added by Drupal.org packaging script on 2015-11-24
version: '8.x-1.0-beta1'
core: '8.x'
project: 'config_inspector'
datestamp: 1448357342
